{
 "title": "Node Overview",
 "tags": [
  "cortexos",
  "host",
  "node"
 ],
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU gauge",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 7, "w": 24, "h": 7 },
   "targets": [
    {
     "expr": "100-(avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))*100)"
    }
   ]
  },
  {
   "title": "CPU ts",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 14, "w": 24, "h": 7 },
   "targets": [
    {
     "expr": "100-(avg by(instance)(rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))*100)"
    }
   ]
  },
  {
   "title": "Memory gauge",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 21, "w": 24, "h": 7 },
   "targets": [
    {
     "expr": "(1-node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes)*100"
    }
   ]
  },
  {
   "title": "Memory ts",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 28, "w": 24, "h": 7 },
   "targets": [
    {
     "expr": "(1-node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes)*100"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 35, "w": 24, "h": 7 },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[5m])+rate(node_disk_written_bytes_total[5m])"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 42, "w": 24, "h": 7 },
   "targets": [
    {
     "expr": "100-(node_filesystem_avail_bytes/node_filesystem_size_bytes*100)"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 49, "w": 24, "h": 7 },
   "targets": [
    { "expr": "node_load1" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "x": 0, "y": 56, "w": 24, "h": 7 },
   "targets": [
    {
     "expr": "node_time_seconds-node_boot_time_seconds"
    }
   ]
  }
 ]
}