set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g mouse on
set -g history-limit 100000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g escape-time 10
set -g focus-events on
set -g status-interval 5
set -g set-clipboard on
setw -g mode-keys vi

unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"
bind s run-shell "~/.tmux/plugins/tmux-resurrect/scripts/save.sh"
bind R run-shell "~/.tmux/plugins/tmux-resurrect/scripts/restore.sh"
bind C-f run-shell "~/.tmux/plugins/tmux-fzf/main.sh"
bind C-e run-shell "~/.tmux/plugins/extrakto/extrakto.tmux"
bind C-s run-shell "~/.tmux/plugins/tmux-sidebar/sidebar.tmux"
bind C-m run-shell "~/.tmux/plugins/tmux-menus/tmux-menus.tmux"
bind C-t choose-tree -Zw
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

set -g @plugin "tmux-plugins/tpm"
set -g @plugin "b0o/tmux-autoreload"
set -g @plugin "tmux-plugins/tmux-cowboy"
set -g @plugin "thepante/tmux-git-autofetch"
set -g @plugin "jaclu/tmux-menus"
set -g @plugin "tmux-plugins/tmux-sidebar"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "noscript/tmux-mighty-scroll"
set -g @plugin "tmux-plugins/tmux-continuum"
set -g @plugin "sainnhe/tmux-fzf"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "spywhere/tmux-named-snapshot"
set -g @plugin "thewtex/tmux-mem-cpu-load"
set -g @plugin "tmux-plugins/tmux-prefix-highlight"
set -g @plugin "laktak/extrakto"
set -g @plugin "bjesus/muxile"
set -g @plugin "kiyoon/treemux"

set -g @continuum-restore "on"
set -g @continuum-save-interval "15"
set -g @resurrect-capture-pane-contents "on"
set -g @resurrect-dir "~/.tmux/resurrect"
set -g @sidebar-tree-command "tree -C"
set -g @prefix_highlight_show_copy_mode "on"
set -g @prefix_highlight_show_sync_mode "on"

run "~/.tmux/plugins/tpm/tpm"
