export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(
  git
  gh
  docker
  docker-compose
  systemd
  tmux
  fzf
  npm
  node
  python
  pip
  zsh-autosuggestions
  zsh-syntax-highlighting
  zsh-completions
)

source "$ZSH/oh-my-zsh.sh"

[ -f "$HOME/.profile" ] && emulate sh -c 'source "$HOME/.profile"'
[ -f /etc/cortexos/host-services.env ] && source /etc/cortexos/host-services.env

export BUN_INSTALL="$HOME/.bun"
path=("$HOME/.local/bin" "$HOME/.bun/bin" "$HOME/.npm-global/bin" $path)
typeset -U path PATH

alias ta='tmux attach -t'
alias tls='tmux list-sessions'
alias tn='tmux new -s'
alias cx='cortex-tmux'
