services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: cortex-home-assistant
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - home_assistant_config:/config
      - /etc/localtime:/etc/localtime:ro

volumes:
  home_assistant_config:
