[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name              systemd
    Tag               host.*
    Read_From_Tail    On

[OUTPUT]
    Name        loki
    Match       *
    Host        loki
    Port        3100
    Labels      job=fluent-bit,host=cortexos
