import { 
	CpuGaugeWidget,
	CpuTemperatureWidget,
	MemoryGaugeWidget,
	MachineSensorsWidget,
	StorageGaugeWidget,
	ServiceOnlineWidget,
	ServiceOfflineWidget,
	ServiceIdleWidget,
	LivePerformanceWidget,
	TopProcessesWidget,
	NetworkGraphWidget,
	TotalDownloadWidget,
	TotalUploadWidget,
	DatabaseOpsWidget,
	MonitoringOpsWidget,
	ContainerOpsWidget,
	DockerStatusWidget,
	UptimeWidget,
	AlertsWidget,
	MailGuardianWidget,
	MailGuardianReviewsWidget
} from './widgets';

export const WIDGET_REGISTRY: Record<string, React.FC> = {
	"cpu-gauge": CpuGaugeWidget,
	"cpu-temperature": CpuTemperatureWidget,
	"memory-gauge": MemoryGaugeWidget,
	"machine-sensors": MachineSensorsWidget,
	"storage-gauge": StorageGaugeWidget,
	"service-online": ServiceOnlineWidget,
	"service-offline": ServiceOfflineWidget,
	"service-idle": ServiceIdleWidget,
	"live-performance": LivePerformanceWidget,
	"top-processes": TopProcessesWidget,
	"network-graph": NetworkGraphWidget,
	"total-download": TotalDownloadWidget,
	"total-upload": TotalUploadWidget,
	"database-ops": DatabaseOpsWidget,
	"monitoring-ops": MonitoringOpsWidget,
	"container-ops": ContainerOpsWidget,
	"docker-status": DockerStatusWidget,
	"uptime": UptimeWidget,
	"alerts": AlertsWidget,
	"mail-guardian": MailGuardianWidget,
	"mail-guardian-reviews": MailGuardianReviewsWidget,
};

export const WIDGET_LABELS: Record<string, string> = {
	"cpu-gauge": "CPU",
	"cpu-temperature": "CPU Temp",
	"memory-gauge": "Memory",
	"machine-sensors": "Machine Sensors",
	"storage-gauge": "Storage",
	"service-online": "Services Online",
	"service-offline": "Services Offline",
	"service-idle": "Services Idle",
	"live-performance": "Live Performance",
	"top-processes": "Top Processes",
	"network-graph": "Network",
	"total-download": "Total Download",
	"total-upload": "Total Upload",
	"database-ops": "Database Ops",
	"monitoring-ops": "Monitoring Ops",
	"container-ops": "Container Ops",
	"docker-status": "Docker Status",
	"uptime": "Host Uptime",
	"alerts": "Alerts",
	"mail-guardian": "Mail Guardian",
	"mail-guardian-reviews": "Mail Reviews",
};
