#!/usr/bin/env bash
# test-9router.sh — discover actual model list via GET /models; write snapshot.
set -euo pipefail

NINEROUTER_BASE_URL="${NINEROUTER_BASE_URL:-}"
NINEROUTER_API_KEY="${NINEROUTER_API_KEY:-}"
SNAPSHOT_OUT="${SNAPSHOT_OUT:-/opt/cortexos/docs/external/9router-models.snapshot.md}"

log() { printf '[test-9router] %s\n' "$*"; }
die() { printf '[test-9router] ERROR: %s\n' "$*" >&2; exit 1; }

# Load secrets if needed
[[ -f /opt/cortexos/.secrets/9router.env ]] && source /opt/cortexos/.secrets/9router.env

[[ -n "$NINEROUTER_BASE_URL" ]] || die "NINEROUTER_BASE_URL not set"
[[ -n "$NINEROUTER_API_KEY" ]]  || die "NINEROUTER_API_KEY not set"

BASE="${NINEROUTER_BASE_URL%/}"
log "probing $BASE/models"

RESPONSE="$(curl -sf \
  -H "Authorization: Bearer $NINEROUTER_API_KEY" \
  -H "Accept: application/json" \
  "${BASE}/models")" \
  || die "GET /models failed"

log "response received ($(echo "$RESPONSE" | wc -c) bytes)"

# Parse model IDs with python3
MODEL_LIST="$(python3 - <<PYEOF
import json, sys
data = json.loads("""$RESPONSE""")
models = data.get("data", data) if isinstance(data, dict) else data
ids = [m.get("id", str(m)) if isinstance(m, dict) else str(m) for m in models]
for i in ids:
    print(i)
PYEOF
)"

COUNT="$(echo "$MODEL_LIST" | grep -c . || true)"
log "discovered $COUNT models"

# Write snapshot
mkdir -p "$(dirname "$SNAPSHOT_OUT")"
{
  printf '# 9Router Model Snapshot\n\n'
  printf '> Auto-generated by test-9router.sh at %s\n' "$(date -u +%FT%TZ)"
  printf '> Source: %s/models\n' "$BASE"
  printf '> This file is a guide only — not a version pin.\n\n'
  printf '## Models (%s)\n\n' "$COUNT"
  while IFS= read -r model; do
    [[ -n "$model" ]] && printf '- `%s`\n' "$model"
  done <<< "$MODEL_LIST"
} > "$SNAPSHOT_OUT"

log "snapshot written to $SNAPSHOT_OUT"
log "TEST PASSED — 9Router responsive, $COUNT models discovered"
