#!/usr/bin/env bash
set -euo pipefail

repo_root="${CORTEXOS_ROOT:-/opt/cortexos}"
secrets_dir="${CORTEXOS_SECRETS_DIR:-$repo_root/.secrets}"
dashboard_env="${CORTEX_DASHBOARD_ENV:-$secrets_dir/cortex-dashboard.env}"
source_env="${CORTEXOS_SOURCE_ENV:-$secrets_dir/cortex.env}"

umask 077
mkdir -p "$secrets_dir"

tmp="$(mktemp "${dashboard_env}.tmp.XXXXXX")"
cleanup() { rm -f "$tmp"; }
trap cleanup EXIT

{
  echo "# Generated by cortex-env-writer.sh. Do not edit by hand."
  echo "CORTEXOS_ROOT=$repo_root"
  if [[ -f "$source_env" ]]; then
    while IFS= read -r line || [[ -n "$line" ]]; do
      [[ -z "$line" || "$line" == \#* ]] && continue
      case "$line" in
        POSTGRES_*|DATABASE_URL=*|NEXTAUTH_*|AUTH_*|CORTEX_*|PAPERCLIP_*|HONCHO_*|HERMES_*|NINE_ROUTER_*|OLLAMA_*)
          printf '%s\n' "$line"
          ;;
      esac
    done < "$source_env"
  fi
} > "$tmp"

install -m 600 "$tmp" "$dashboard_env"
trap - EXIT
rm -f "$tmp"
