services:
  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: cortex-redis-exporter
    restart: unless-stopped
    env_file:
      - ../../.secrets/redis.env
    command:
      - --redis.addr=redis://redis:6379
      - --redis.password=${REDIS_PASSWORD}
    ports:
      - "127.0.0.1:9121:9121"
    networks:
      - cortex-db

networks:
  cortex-db:
    external: true
