/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTerminalRouteImport } from './routes/_authenticated.terminal'
import { Route as AuthenticatedSystemdRouteImport } from './routes/_authenticated.systemd'
import { Route as AuthenticatedStorageRouteImport } from './routes/_authenticated.storage'
import { Route as AuthenticatedSchedulerRouteImport } from './routes/_authenticated.scheduler'
import { Route as AuthenticatedProcessesRouteImport } from './routes/_authenticated.processes'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated.overview'
import { Route as AuthenticatedNetworkRouteImport } from './routes/_authenticated.network'
import { Route as AuthenticatedMailGuardianRouteImport } from './routes/_authenticated.mail-guardian'
import { Route as AuthenticatedIncusRouteImport } from './routes/_authenticated.incus'
import { Route as AuthenticatedHealthcheckRouteImport } from './routes/_authenticated.healthcheck'
import { Route as AuthenticatedHeadroomRouteImport } from './routes/_authenticated.headroom'
import { Route as AuthenticatedDockerRouteImport } from './routes/_authenticated.docker'
import { Route as AuthenticatedBackupsRouteImport } from './routes/_authenticated.backups'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated.audit'
import { Route as AuthenticatedAppsRouteImport } from './routes/_authenticated.apps'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated.approvals'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated.alerts'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated.agents'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedSystemdUnitRouteImport } from './routes/_authenticated.systemd.$unit'
import { Route as AuthenticatedIncusNameRouteImport } from './routes/_authenticated.incus.$name'
import { Route as AuthenticatedDockerIdRouteImport } from './routes/_authenticated.docker.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated.admin.services'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated.admin.projects'
import { Route as AuthenticatedAdminEnvBrowserRouteImport } from './routes/_authenticated.admin.env-browser'
import { Route as AuthenticatedAdminBadgesRouteImport } from './routes/_authenticated.admin.badges'
import { Route as AuthenticatedAdminAlertsRouteImport } from './routes/_authenticated.admin.alerts'
import { Route as AuthenticatedAdminAccountRouteImport } from './routes/_authenticated.admin.account'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTerminalRoute = AuthenticatedTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSystemdRoute = AuthenticatedSystemdRouteImport.update({
  id: '/systemd',
  path: '/systemd',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStorageRoute = AuthenticatedStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSchedulerRoute = AuthenticatedSchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProcessesRoute = AuthenticatedProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNetworkRoute = AuthenticatedNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMailGuardianRoute =
  AuthenticatedMailGuardianRouteImport.update({
    id: '/mail-guardian',
    path: '/mail-guardian',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIncusRoute = AuthenticatedIncusRouteImport.update({
  id: '/incus',
  path: '/incus',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHealthcheckRoute =
  AuthenticatedHealthcheckRouteImport.update({
    id: '/healthcheck',
    path: '/healthcheck',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHeadroomRoute = AuthenticatedHeadroomRouteImport.update({
  id: '/headroom',
  path: '/headroom',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDockerRoute = AuthenticatedDockerRouteImport.update({
  id: '/docker',
  path: '/docker',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBackupsRoute = AuthenticatedBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppsRoute = AuthenticatedAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSystemdUnitRoute =
  AuthenticatedSystemdUnitRouteImport.update({
    id: '/$unit',
    path: '/$unit',
    getParentRoute: () => AuthenticatedSystemdRoute,
  } as any)
const AuthenticatedIncusNameRoute = AuthenticatedIncusNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => AuthenticatedIncusRoute,
} as any)
const AuthenticatedDockerIdRoute = AuthenticatedDockerIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDockerRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEnvBrowserRoute =
  AuthenticatedAdminEnvBrowserRouteImport.update({
    id: '/env-browser',
    path: '/env-browser',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBadgesRoute =
  AuthenticatedAdminBadgesRouteImport.update({
    id: '/badges',
    path: '/badges',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAlertsRoute =
  AuthenticatedAdminAlertsRouteImport.update({
    id: '/alerts',
    path: '/alerts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAccountRoute =
  AuthenticatedAdminAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/agents': typeof AuthenticatedAgentsRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/apps': typeof AuthenticatedAppsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/docker': typeof AuthenticatedDockerRouteWithChildren
  '/headroom': typeof AuthenticatedHeadroomRoute
  '/healthcheck': typeof AuthenticatedHealthcheckRoute
  '/incus': typeof AuthenticatedIncusRouteWithChildren
  '/mail-guardian': typeof AuthenticatedMailGuardianRoute
  '/network': typeof AuthenticatedNetworkRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/processes': typeof AuthenticatedProcessesRoute
  '/scheduler': typeof AuthenticatedSchedulerRoute
  '/storage': typeof AuthenticatedStorageRoute
  '/systemd': typeof AuthenticatedSystemdRouteWithChildren
  '/terminal': typeof AuthenticatedTerminalRoute
  '/admin/account': typeof AuthenticatedAdminAccountRoute
  '/admin/alerts': typeof AuthenticatedAdminAlertsRoute
  '/admin/badges': typeof AuthenticatedAdminBadgesRoute
  '/admin/env-browser': typeof AuthenticatedAdminEnvBrowserRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/docker/$id': typeof AuthenticatedDockerIdRoute
  '/incus/$name': typeof AuthenticatedIncusNameRoute
  '/systemd/$unit': typeof AuthenticatedSystemdUnitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/agents': typeof AuthenticatedAgentsRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/apps': typeof AuthenticatedAppsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/docker': typeof AuthenticatedDockerRouteWithChildren
  '/headroom': typeof AuthenticatedHeadroomRoute
  '/healthcheck': typeof AuthenticatedHealthcheckRoute
  '/incus': typeof AuthenticatedIncusRouteWithChildren
  '/mail-guardian': typeof AuthenticatedMailGuardianRoute
  '/network': typeof AuthenticatedNetworkRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/processes': typeof AuthenticatedProcessesRoute
  '/scheduler': typeof AuthenticatedSchedulerRoute
  '/storage': typeof AuthenticatedStorageRoute
  '/systemd': typeof AuthenticatedSystemdRouteWithChildren
  '/terminal': typeof AuthenticatedTerminalRoute
  '/admin/account': typeof AuthenticatedAdminAccountRoute
  '/admin/alerts': typeof AuthenticatedAdminAlertsRoute
  '/admin/badges': typeof AuthenticatedAdminBadgesRoute
  '/admin/env-browser': typeof AuthenticatedAdminEnvBrowserRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/docker/$id': typeof AuthenticatedDockerIdRoute
  '/incus/$name': typeof AuthenticatedIncusNameRoute
  '/systemd/$unit': typeof AuthenticatedSystemdUnitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/apps': typeof AuthenticatedAppsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/backups': typeof AuthenticatedBackupsRoute
  '/_authenticated/docker': typeof AuthenticatedDockerRouteWithChildren
  '/_authenticated/headroom': typeof AuthenticatedHeadroomRoute
  '/_authenticated/healthcheck': typeof AuthenticatedHealthcheckRoute
  '/_authenticated/incus': typeof AuthenticatedIncusRouteWithChildren
  '/_authenticated/mail-guardian': typeof AuthenticatedMailGuardianRoute
  '/_authenticated/network': typeof AuthenticatedNetworkRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/processes': typeof AuthenticatedProcessesRoute
  '/_authenticated/scheduler': typeof AuthenticatedSchedulerRoute
  '/_authenticated/storage': typeof AuthenticatedStorageRoute
  '/_authenticated/systemd': typeof AuthenticatedSystemdRouteWithChildren
  '/_authenticated/terminal': typeof AuthenticatedTerminalRoute
  '/_authenticated/admin/account': typeof AuthenticatedAdminAccountRoute
  '/_authenticated/admin/alerts': typeof AuthenticatedAdminAlertsRoute
  '/_authenticated/admin/badges': typeof AuthenticatedAdminBadgesRoute
  '/_authenticated/admin/env-browser': typeof AuthenticatedAdminEnvBrowserRoute
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/docker/$id': typeof AuthenticatedDockerIdRoute
  '/_authenticated/incus/$name': typeof AuthenticatedIncusNameRoute
  '/_authenticated/systemd/$unit': typeof AuthenticatedSystemdUnitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/agents'
    | '/alerts'
    | '/approvals'
    | '/apps'
    | '/audit'
    | '/backups'
    | '/docker'
    | '/headroom'
    | '/healthcheck'
    | '/incus'
    | '/mail-guardian'
    | '/network'
    | '/overview'
    | '/processes'
    | '/scheduler'
    | '/storage'
    | '/systemd'
    | '/terminal'
    | '/admin/account'
    | '/admin/alerts'
    | '/admin/badges'
    | '/admin/env-browser'
    | '/admin/projects'
    | '/admin/services'
    | '/admin/users'
    | '/docker/$id'
    | '/incus/$name'
    | '/systemd/$unit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/agents'
    | '/alerts'
    | '/approvals'
    | '/apps'
    | '/audit'
    | '/backups'
    | '/docker'
    | '/headroom'
    | '/healthcheck'
    | '/incus'
    | '/mail-guardian'
    | '/network'
    | '/overview'
    | '/processes'
    | '/scheduler'
    | '/storage'
    | '/systemd'
    | '/terminal'
    | '/admin/account'
    | '/admin/alerts'
    | '/admin/badges'
    | '/admin/env-browser'
    | '/admin/projects'
    | '/admin/services'
    | '/admin/users'
    | '/docker/$id'
    | '/incus/$name'
    | '/systemd/$unit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/agents'
    | '/_authenticated/alerts'
    | '/_authenticated/approvals'
    | '/_authenticated/apps'
    | '/_authenticated/audit'
    | '/_authenticated/backups'
    | '/_authenticated/docker'
    | '/_authenticated/headroom'
    | '/_authenticated/healthcheck'
    | '/_authenticated/incus'
    | '/_authenticated/mail-guardian'
    | '/_authenticated/network'
    | '/_authenticated/overview'
    | '/_authenticated/processes'
    | '/_authenticated/scheduler'
    | '/_authenticated/storage'
    | '/_authenticated/systemd'
    | '/_authenticated/terminal'
    | '/_authenticated/admin/account'
    | '/_authenticated/admin/alerts'
    | '/_authenticated/admin/badges'
    | '/_authenticated/admin/env-browser'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/users'
    | '/_authenticated/docker/$id'
    | '/_authenticated/incus/$name'
    | '/_authenticated/systemd/$unit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/terminal': {
      id: '/_authenticated/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof AuthenticatedTerminalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/systemd': {
      id: '/_authenticated/systemd'
      path: '/systemd'
      fullPath: '/systemd'
      preLoaderRoute: typeof AuthenticatedSystemdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/storage': {
      id: '/_authenticated/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof AuthenticatedStorageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scheduler': {
      id: '/_authenticated/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof AuthenticatedSchedulerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/processes': {
      id: '/_authenticated/processes'
      path: '/processes'
      fullPath: '/processes'
      preLoaderRoute: typeof AuthenticatedProcessesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/network': {
      id: '/_authenticated/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AuthenticatedNetworkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mail-guardian': {
      id: '/_authenticated/mail-guardian'
      path: '/mail-guardian'
      fullPath: '/mail-guardian'
      preLoaderRoute: typeof AuthenticatedMailGuardianRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incus': {
      id: '/_authenticated/incus'
      path: '/incus'
      fullPath: '/incus'
      preLoaderRoute: typeof AuthenticatedIncusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/healthcheck': {
      id: '/_authenticated/healthcheck'
      path: '/healthcheck'
      fullPath: '/healthcheck'
      preLoaderRoute: typeof AuthenticatedHealthcheckRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/headroom': {
      id: '/_authenticated/headroom'
      path: '/headroom'
      fullPath: '/headroom'
      preLoaderRoute: typeof AuthenticatedHeadroomRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/docker': {
      id: '/_authenticated/docker'
      path: '/docker'
      fullPath: '/docker'
      preLoaderRoute: typeof AuthenticatedDockerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/backups': {
      id: '/_authenticated/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AuthenticatedBackupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps': {
      id: '/_authenticated/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/systemd/$unit': {
      id: '/_authenticated/systemd/$unit'
      path: '/$unit'
      fullPath: '/systemd/$unit'
      preLoaderRoute: typeof AuthenticatedSystemdUnitRouteImport
      parentRoute: typeof AuthenticatedSystemdRoute
    }
    '/_authenticated/incus/$name': {
      id: '/_authenticated/incus/$name'
      path: '/$name'
      fullPath: '/incus/$name'
      preLoaderRoute: typeof AuthenticatedIncusNameRouteImport
      parentRoute: typeof AuthenticatedIncusRoute
    }
    '/_authenticated/docker/$id': {
      id: '/_authenticated/docker/$id'
      path: '/$id'
      fullPath: '/docker/$id'
      preLoaderRoute: typeof AuthenticatedDockerIdRouteImport
      parentRoute: typeof AuthenticatedDockerRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/env-browser': {
      id: '/_authenticated/admin/env-browser'
      path: '/env-browser'
      fullPath: '/admin/env-browser'
      preLoaderRoute: typeof AuthenticatedAdminEnvBrowserRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/badges': {
      id: '/_authenticated/admin/badges'
      path: '/badges'
      fullPath: '/admin/badges'
      preLoaderRoute: typeof AuthenticatedAdminBadgesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/alerts': {
      id: '/_authenticated/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AuthenticatedAdminAlertsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/account': {
      id: '/_authenticated/admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AuthenticatedAdminAccountRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAccountRoute: typeof AuthenticatedAdminAccountRoute
  AuthenticatedAdminAlertsRoute: typeof AuthenticatedAdminAlertsRoute
  AuthenticatedAdminBadgesRoute: typeof AuthenticatedAdminBadgesRoute
  AuthenticatedAdminEnvBrowserRoute: typeof AuthenticatedAdminEnvBrowserRoute
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAccountRoute: AuthenticatedAdminAccountRoute,
  AuthenticatedAdminAlertsRoute: AuthenticatedAdminAlertsRoute,
  AuthenticatedAdminBadgesRoute: AuthenticatedAdminBadgesRoute,
  AuthenticatedAdminEnvBrowserRoute: AuthenticatedAdminEnvBrowserRoute,
  AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDockerRouteChildren {
  AuthenticatedDockerIdRoute: typeof AuthenticatedDockerIdRoute
}

const AuthenticatedDockerRouteChildren: AuthenticatedDockerRouteChildren = {
  AuthenticatedDockerIdRoute: AuthenticatedDockerIdRoute,
}

const AuthenticatedDockerRouteWithChildren =
  AuthenticatedDockerRoute._addFileChildren(AuthenticatedDockerRouteChildren)

interface AuthenticatedIncusRouteChildren {
  AuthenticatedIncusNameRoute: typeof AuthenticatedIncusNameRoute
}

const AuthenticatedIncusRouteChildren: AuthenticatedIncusRouteChildren = {
  AuthenticatedIncusNameRoute: AuthenticatedIncusNameRoute,
}

const AuthenticatedIncusRouteWithChildren =
  AuthenticatedIncusRoute._addFileChildren(AuthenticatedIncusRouteChildren)

interface AuthenticatedSystemdRouteChildren {
  AuthenticatedSystemdUnitRoute: typeof AuthenticatedSystemdUnitRoute
}

const AuthenticatedSystemdRouteChildren: AuthenticatedSystemdRouteChildren = {
  AuthenticatedSystemdUnitRoute: AuthenticatedSystemdUnitRoute,
}

const AuthenticatedSystemdRouteWithChildren =
  AuthenticatedSystemdRoute._addFileChildren(AuthenticatedSystemdRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedAppsRoute: typeof AuthenticatedAppsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBackupsRoute: typeof AuthenticatedBackupsRoute
  AuthenticatedDockerRoute: typeof AuthenticatedDockerRouteWithChildren
  AuthenticatedHeadroomRoute: typeof AuthenticatedHeadroomRoute
  AuthenticatedHealthcheckRoute: typeof AuthenticatedHealthcheckRoute
  AuthenticatedIncusRoute: typeof AuthenticatedIncusRouteWithChildren
  AuthenticatedMailGuardianRoute: typeof AuthenticatedMailGuardianRoute
  AuthenticatedNetworkRoute: typeof AuthenticatedNetworkRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedProcessesRoute: typeof AuthenticatedProcessesRoute
  AuthenticatedSchedulerRoute: typeof AuthenticatedSchedulerRoute
  AuthenticatedStorageRoute: typeof AuthenticatedStorageRoute
  AuthenticatedSystemdRoute: typeof AuthenticatedSystemdRouteWithChildren
  AuthenticatedTerminalRoute: typeof AuthenticatedTerminalRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedAppsRoute: AuthenticatedAppsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBackupsRoute: AuthenticatedBackupsRoute,
  AuthenticatedDockerRoute: AuthenticatedDockerRouteWithChildren,
  AuthenticatedHeadroomRoute: AuthenticatedHeadroomRoute,
  AuthenticatedHealthcheckRoute: AuthenticatedHealthcheckRoute,
  AuthenticatedIncusRoute: AuthenticatedIncusRouteWithChildren,
  AuthenticatedMailGuardianRoute: AuthenticatedMailGuardianRoute,
  AuthenticatedNetworkRoute: AuthenticatedNetworkRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedProcessesRoute: AuthenticatedProcessesRoute,
  AuthenticatedSchedulerRoute: AuthenticatedSchedulerRoute,
  AuthenticatedStorageRoute: AuthenticatedStorageRoute,
  AuthenticatedSystemdRoute: AuthenticatedSystemdRouteWithChildren,
  AuthenticatedTerminalRoute: AuthenticatedTerminalRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
